version: '3.0'
services:
  
  db:
    container_name: lembrete-postgres
    image: postgres:10.5-alpine
    environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_DB=lembretes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
       - 5432:5432
    networks:
       - lembrete-network

  api:
    image: lembrete-api:v1-prod
    ports:
        - 8081:8081
    environment:
        - LEMBRETES_DATABASE_URL=jdbc:postgresql://lembrete-postgres:5432/lembretes
        - LEMBRETES_DATABASE_USERNAME=postgres
        - LEMBRETES_DATABASE_PASSWORD=postgres
    depends_on:
        db:
          condition: service_healthy
    networks:
        - lembrete-network

networks:
  lembrete-network: 
    driver: bridge
