version: '3.0'
services:

  bd:
    container_name: teste-bd
    image: mysql:5
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_DATABASE: teste
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306